#### Introduction to Numpy
##### 1. Write a NumPy program to multiply two given arrays of same size element-by-element.
##### 2. Write a NumPy program to find the missing data in a given array.
##### 3. Write a NumPy program to test whether each element of a 1-D array is also present in a second array.
##### 4. Write a NumPy program to save a NumPy array to a text file.
##### 5. Write a NumPy program to Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive.

In [6]:
# Importing the NumPy library with an alias 'np'
import numpy as np 

# Creating two NumPy arrays 'nums1' and 'nums2' containing 3x3 matrices
nums1 = np.array([[2, 5, 2], [1,2,3], [1, 5, 5]])

nums2 = np.array([[5, 3, 4], [3,2,4],[3, 2, 5]])

# Printing the contents of 'nums1' array
print("Array1:") 
print(nums1)

# Printing the contents of 'nums2' array
print("Array2:") 
print(nums2)

# Performing element-wise multiplication of arrays 'nums1' and 'nums2' using np.multiply()
# This operation multiplies corresponding elements of the two arrays
print("\nMultiply two given arrays:")
print(np.multiply(nums1, nums2))

Array1:
[[2 5 2]
 [1 2 3]
 [1 5 5]]
Array2:
[[5 3 4]
 [3 2 4]
 [3 2 5]]

Multiply two given arrays:
[[10 15  8]
 [ 3  4 12]
 [ 3 10 25]]


In [8]:
import numpy as np
 
# Creating a NumPy array 'nums' with provided values, including NaN (Not a Number)
nums = np.array([[2, 7, 5, np.nan],
                 [0, 4, 3, 19],
                 [5, np.nan, 1, np.nan]])

print("Original array:")
print(nums)

# This function returns a boolean array of the same shape as 'nums', where True represents NaN values
print("\nFind the missing data of the said array:")
print(np.isnan(nums))


Original array:
[[ 2.  7.  5. nan]
 [ 0.  4.  3. 19.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False False  True]
 [False False False False]
 [False  True False  True]]


In [10]:
import numpy as np
array1 = np.array([0, 10, 20, 30, 40])
print("Array1: ", array1)

array2 = [0, 30]
print("Array2: ", array2)

print("Compare each element of array1 and array2")
print(np.in1d(array1, array2))

Array1:  [ 0 10 20 30 40]
Array2:  [0, 30]
Compare each element of array1 and array2
[ True False False  True False]


In [12]:
import numpy as np
 
# Creating an array
List = [1, 2, 3, 4, 5]
Array = numpy.array(List)
 
# Displaying the array
print('Array:\n', Array)
file = open("file1.txt", "w+")
 
# Saving the array in a text file
content = str(Array)
file.write(content)
file.close()
 
# Displaying the contents of the text file
file = open("file1.txt", "r")
content = file.read()
 
print("\nContent in file1.txt:\n", content)
file.close()

Array:
 [1 2 3 4 5]

Content in file1.txt:
 [1 2 3 4 5]


In [13]:
import numpy as np

# Generating an array of 30 evenly spaced values from 2.5 to 6.5 inclusive
x = np.linspace(2.5, 6.5, 30)

print(x)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


#### Introduction to Pandas (Series and Dataframes)
##### 1. Write a Pandas program to convert Series of lists to one Series.
##### 2. Write a Pandas program to create a subset of a given series based on value and condition.
##### 3. Write a Pandas program to display most frequent value in a given series and replace everything else as 'Other' in the series.
##### 4. Write a Pandas program to find the positions of numbers that are multiples of 5 of a given series.
##### 5. Write a Pandas program to calculate the number of characters in each word in a given series.
##### 6. Write a Pandas program to convert year-month string to dates adding a specified day of the month.
##### 7. Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels.
##### 8. Write a Pandas program to select the rows where the number of attempts in the examination is greater than 2.
##### 9. Write a Pandas program to append a new row 'k' to data frame with given values for each column. Now delete the new row and return the original DataFrame.
##### 10. Write a Pandas program to sort the DataFrame first by 'name' in descending order, then by 'score' in ascending order.
##### 11. Write a Pandas program to replace the &#39;qualify&#39; column contains the values 'yes' and 'no' with True and False.
##### 12. Write a Pandas program to remove infinite values from a given DataFrame.

In [17]:
import pandas as pd
x = pd.Series([['Red', 'Green', 'White'],['Red', 'Black'],['Yellow']])
print("Original Series of list")
print(x)
x = x.apply(pd.Series).stack().reset_index(drop=True)
print("One Series")
print(x)

Original Series of list
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object
One Series
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object


In [18]:
import pandas as pd
s = pd.Series([0,1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s < n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64


In [19]:
import pandas as pd
import numpy as np
num_series = pd.Series(np.random.randint(1, 5, [15]))
print("Original Series:")
print(num_series)
print("Top 2 Freq:", num_series.value_counts())
result = num_series[~num_series.isin(num_series.value_counts().index[:1])] = 'Other'
print(num_series)

Original Series:
0     3
1     3
2     1
3     1
4     2
5     3
6     1
7     1
8     4
9     2
10    3
11    2
12    4
13    2
14    1
dtype: int32
Top 2 Freq: 1    5
3    4
2    4
4    2
dtype: int64
0     Other
1     Other
2         1
3         1
4     Other
5     Other
6         1
7         1
8     Other
9     Other
10    Other
11    Other
12    Other
13    Other
14        1
dtype: object


In [20]:
import pandas as pd
import numpy as np
num_series = pd.Series(np.random.randint(1, 10, 9))
print("Original Series:")
print(num_series)
result = np.where(num_series % 5==0)
print("Positions of numbers that are multiples of 5:")
print(result)

Original Series:
0    9
1    4
2    8
3    2
4    2
5    9
6    5
7    7
8    1
dtype: int32
Positions of numbers that are multiples of 5:
(array([6], dtype=int64),)


In [21]:
import pandas as pd
series1 = pd.Series(['Php', 'Python', 'Java', 'C#'])
print("Original Series:")
print(series1)
result = series1.map(lambda x: len(x))
print("\nNumber of characters in each word in the said series:")
print(result)

Original Series:
0       Php
1    Python
2      Java
3        C#
dtype: object

Number of characters in each word in the said series:
0    3
1    6
2    4
3    2
dtype: int64


In [22]:
import pandas as pd
from dateutil.parser import parse
date_series = pd.Series(['Jan 2015', 'Feb 2016', 'Mar 2017', 'Apr 2018', 'May 2019'])
print("Original Series:")
print(date_series)
print("\nNew dates:")
result = date_series.map(lambda d: parse('11 ' + d))
print(result)

Original Series:
0    Jan 2015
1    Feb 2016
2    Mar 2017
3    Apr 2018
4    May 2019
dtype: object

New dates:
0   2015-01-11
1   2016-02-11
2   2017-03-11
3   2018-04-11
4   2019-05-11
dtype: datetime64[ns]


In [23]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


In [25]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Ram', 'John', 'Kima', 'James', 'Bobby', 'Mohan', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts' : [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("Number of attempts in the examination is greater than 2:")
print(df[df['attempts'] > 2])

Number of attempts in the examination is greater than 2:
    name  score  attempts qualify
b   John    9.0         3      no
d  James    NaN         3      no
f  Mohan   20.0         3     yes


In [26]:
import pandas as pd
import numpy as np
exam_data  = {'name': ['Ram', 'Dima', 'Katherine', 'James', 'Bobby', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data , index=labels)
print("Original rows:")
print(df)
print("\nAppend a new row:")
df.loc['k'] = [1, 'Suresh', 'yes', 15.5]
print("Print all records after insert a new record:")
print(df)
print("\nDelete the new row and display the original  rows:")
df = df.drop('k')
print(df)

Original rows:
        name  score  attempts qualify
a        Ram   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Bobby    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

Append a new row:
Print all records after insert a new record:
        name   score attempts qualify
a        Ram    12.5        1     yes
b       Dima     9.0        3      no
c  Katherine    16.5        2     yes
d      James     NaN        3      no
e      Bobby     9.0        2      no
f    Michael    20.0        3     yes
g    Matthew    14.5        1     yes
h      Laura     NaN        1      no
i      Kevin     8.0        2      no
j      Jonas    19.0        1     yes
k          1  Suresh      yes    15.5

Delete the new row and display the original  r

In [27]:
import pandas as pd
import numpy as np
exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data , index=labels)
print("Orginal rows:")
print(df)
df = df.sort_values(by=['name', 'score'], ascending=[False, True])
print("Sort the data frame first by ‘name’ in descending order, then by ‘score’ in ascending order:")
print(df)

Orginal rows:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
Sort the data frame first by ‘name’ in descending order, then by ‘score’ in ascending order:
        name  score  attempts qualify
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
b       Dima    9.0         3      no
a  Anastasia   12.5         1     yes


In [28]:
import pandas as pd
import numpy as np
exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data , index=labels)
print("Original rows:")
print(df)
print("\nReplace the 'qualify' column contains the values 'yes' and 'no'  with True and  False:")
df['qualify'] = df['qualify'].map({'yes': True, 'no': False})
print(df)

Original rows:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

Replace the 'qualify' column contains the values 'yes' and 'no'  with True and  False:
        name  score  attempts  qualify
a  Anastasia   12.5         1     True
b       Dima    9.0         3    False
c  Katherine   16.5         2     True
d      James    NaN         3    False
e      Emily    9.0         2    False
f    Michael   20.0         3     True
g    Matthew   14.5         1     True
h      Laura    NaN         1    False
i      Kevin    8.0         2    False
j      Jonas   19.0         1     True


In [29]:
import pandas as pd
import numpy as np
df = pd.DataFrame([1000, 2000, 3000, -4000, np.inf, -np.inf])
print("Original DataFrame:")
print(df)
print("Removing infinite values:")
df = df.replace([np.inf, -np.inf], np.nan)
print(df)

Original DataFrame:
        0
0  1000.0
1  2000.0
2  3000.0
3 -4000.0
4     inf
5    -inf
Removing infinite values:
        0
0  1000.0
1  2000.0
2  3000.0
3 -4000.0
4     NaN
5     NaN
