In [3]:
#Create a vector (array) of 1XN dimension representing N-
#dimensional feature vector of a sample. Write a program to
#compute the mean and variance of the elements present in the array.
import numpy as np

# Create a vector of 1xN dimension
vector = np.array([1, 2, 3, 4, 5])

# Calculate the mean
mean = np.mean(vector)

# Calculate the variance (sample variance)
variance = np.var(vector, ddof=1)

# Print the mean and variance
print("Mean: ", mean)
print("Variance: ", variance)

Mean:  3.0
Variance:  2.5


In [8]:
#Create two vectors each of dimension 1XM each representing N-
#dimensional feature vector of a sample. Write a program to
#compute the Covariance between them.
import numpy as np

# Create two vectors of 1xM dimension
vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([2, 3, 4, 5, 6])

# Calculate the covariance
covariance = np.cov(vector1, vector2, ddof=1)[0][1]

# Print the covariance
print("Covariance: ", covariance)

Covariance:  2.5


In [5]:
#Create two vectors each of dimension 1XN. Write a program to
#compute the Correlation between them.
import numpy as np

# Create two vectors of 1xN dimension
vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([2, 3, 4, 5, 6])

# Calculate the correlation coefficient
correlation = np.corrcoef(vector1, vector2)[0][1]

# Print the correlation coefficient
print("Correlation: ", correlation)

Correlation:  0.9999999999999999


In [6]:
#Create a Matrix of MXN dimension representing the M-dimensional
#feature vector for N number of samples i. e (i,j)th entry of the matrix
#represents the ith feature of jth sample. Write a program to compute
#the covariance matrix and correlation matrix. Comment on
#takeaways from these matrixes.
import numpy as np

# Create a MxN dimension matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculate the covariance matrix
covariance_matrix = np.cov(matrix, rowvar=False)

# Calculate the correlation matrix
correlation_matrix = np.corrcoef(matrix, rowvar=False)

# Print the covariance matrix
print("Covariance matrix:")
print(covariance_matrix)

# Print the correlation matrix
print("Correlation matrix:")
print(correlation_matrix)

Covariance matrix:
[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]
Correlation matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
